import sys
from pathlib import Path
# Ensure project root is in sys.path so imports work from visualize_models_influence folder
_root = Path(__file__).resolve().parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

def plot_heatmap(data, labels, title, save_path):
    plt.figure(figsize=(10, 8))
    sns.heatmap(data, annot=False, cmap='viridis', xticklabels=labels, yticklabels=labels)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(save_path, dpi=200)
    plt.close()
    print(f"🖼️ Heatmap saved: {save_path}")

def main():
    base_dir = Path(r"c:\Users\2213144\practice\result_csv_residual")
    output_dir = Path(r"c:\Users\2213144\practice\picture_analysis")
    output_dir.mkdir(exist_ok=True)

    # 1. iTransformer Attention (Variable Correlation)
    it_path = base_dir / "iTransformer" / "iTransformer_spring_unified_internals.npz"
    if it_path.exists():
        data = np.load(it_path)
        attn = data['attention_map'] # (B, N, N) or (N, N)
        if attn.ndim == 3:
            attn = attn.mean(axis=0)
        
        labels = data['feature_names']
        plot_heatmap(attn, labels, "iTransformer: Variable-to-Variable Attention", output_dir / "iTransformer_attention_spring.png")

    # 2. Hybrid FiLM Attention
    film_path = base_dir / "Hybrid_FiLM_Ablation" / "Hybrid_FiLM_Ablation_spring_separated_internals.npz"
    if film_path.exists():
        data = np.load(film_path)
        # FiLM models might have attention_map or modulation heatmaps
        if 'attention_map' in data:
            attn = data['attention_map']
            if attn.ndim == 3:
                attn = attn.mean(axis=0)
            
            # For Hybrid models, feature_names are usually exog features
            labels = data['feature_names']
            plot_heatmap(attn, labels, "Hybrid FiLM: Feature Attention Map", output_dir / "Hybrid_FiLM_attention_spring.png")
            
        # Also plot alpha modulation if available (representing variable importance/correlation)
        if 'alpha_vt' in data:
            alpha = data['alpha_vt'] # (B, N, d) or similar
            if alpha.ndim == 3:
                alpha = alpha.mean(axis=0) # (N, d)
            # Just take the magnitude over d_model
            alpha_mag = np.abs(alpha).mean(axis=1)
            # This is 1D, but we can plot it as a bar chart or single-row heatmap
            plt.figure(figsize=(10, 2))
            sns.heatmap(alpha_mag.reshape(1, -1), annot=True, xticklabels=data['feature_names'], yticklabels=["Importance"])
            plt.title("FiLM Alpha Modulation (Variable Importance)")
            plt.tight_layout()
            plt.savefig(output_dir / "FiLM_alpha_importance.png")
            plt.close()
            print(f"🖼️ Heatmap saved: {output_dir / 'FiLM_alpha_importance.png'}")

    # 3. MMK Routing Probabilities
    # We need to find the file generated by the recent run.
    # It should be in result_csv/MMK/...
    # Let's search for .npz files in MMK directory
    mmk_dir = Path(r"c:\Users\2213144\practice\result_csv\MMK")
    if mmk_dir.exists():
        # Find the latest npz file
        npz_files = list(mmk_dir.glob("*_internals.npz"))
        if npz_files:
            latest_mmk = max(npz_files, key=lambda f: f.stat().st_mtime)
            print(f"Loading MMK internals from: {latest_mmk}")
            
            data = np.load(latest_mmk)
            # keys: routing_probs (B, F, L, n_exp) or (B, F, 1, n_exp)
            if 'routing_probs' in data:
                probs = data['routing_probs'] # (B, F, L, n_exp)
                # Average over Batch and Time (L)
                # We want to see: For each Feature (F), which Experts (n_exp) are active?
                if probs.ndim == 4:
                    mean_probs = probs.mean(axis=(0, 2)) # (F, n_exp)
                elif probs.ndim == 3:
                     mean_probs = probs.mean(axis=0) # (F, n_exp) assumed (B, F, n_exp)
                else:
                    mean_probs = None
                
                if mean_probs is not None:
                    # Feature names
                    # MMK Feature names might not be saved in npz depending on implementation
                    # But we know them: Target + Exog (Cyclic)
                    # Let's try to get from data or use default list
                    if 'feature_names' in data:
                        f_names = data['feature_names']
                    else:
                        # Fallback for Cyclic
                        f_names = ["Power", "Temp", "Precip", "Solar", "W_Sin", "W_Cos", "M_Sin", "M_Cos", "Hol", "Rest"]
                        # Adjust length if mismatch
                        if len(f_names) != mean_probs.shape[0]:
                            f_names = [f"Feat_{i}" for i in range(mean_probs.shape[0])]
                            
                    plt.figure(figsize=(10, 6))
                    sns.heatmap(mean_probs, annot=True, cmap='Blues', xticklabels=[f"Exp_{i}" for i in range(mean_probs.shape[1])], yticklabels=f_names)
                    plt.title("MMK Hybrid: Expert Utilization per Feature")
                    plt.tight_layout()
                    save_path = output_dir / "MMK_Hybrid_Expert_Utilization.png"
                    plt.savefig(save_path)
                    plt.close()
                    print(f"🖼️  Heatmap saved: {save_path}")

if __name__ == "__main__":
    main()
